FROM prom/prometheus:latest

COPY --chmod=644 prometheus.yml /etc/prometheus/prometheus.yml
COPY --chmod=644 prometheus/alerts.yml /etc/prometheus/alerts.yml

EXPOSE 9090

CMD [ "--config.file=/etc/prometheus/prometheus.yml", \
      "--storage.tsdb.path=/prometheus", \
      "--web.console.libraries=/etc/prometheus/console_libraries", \
      "--web.console.templates=/etc/prometheus/consoles", \
      "--storage.tsdb.retention.time=200h", \
      "--web.enable-lifecycle" ]